### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by nrqrmz**
This is our final version of the Youtube clone project.

Margins have been fixed.
Some icons were added.
Icons below the video were rearranged.
README file updated according to Microverse templates.

### CODE REVIEW

**Comment by voscarmv** [comment]
# Pull Request Under Review by Oscar Mier (TSE) 👨‍💻 🐦

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice progress, team! 🖥️ 👀 ✨ 
## However, some changes are still required... 🧰 🔨 🔧 
- The YouTube logo image on your navbar is broken. Please fix this. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/navbar_logo_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
image
- The navbar must have three embedded images on the rightmost part of the navbar that represent icons and/or an avatar ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
image
- Your video description is missing the SUBSCRIBE button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
image
- Your video thumbnails are missing the number of views. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_views_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
image
- Please make proper usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) elements. They should be "appropriately sized and positioned" (as described in Odin project description) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright)

### Submit these changes and request a new code review! 😄 👍 
### Questions of comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻 🗨️ 🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by nrqrmz** [comment]
Add images to navbar
Fix Youtube logo on navbar
Add subscribe button
Add views counter
Add README file

**Comment by BrittanyBlake** [comment]
### Pull request under review by Brittany Blake (TSE)

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @nrqrmz and @tadeuasarro! 👋 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The [HTML validator](https://validator.w3.org) is still showing an error 👇 

Screen Shot 2020-06-09 at 10 36 39 PM

- _hint: I believe this issue stems from the fact that you don't have <meta> tag defined in the head of your HTML doc. please take a look at this [article](https://www.w3schools.com/html/html_head.asp) for more information_

- [ ] The embedded images in the navbar are not properly positioned. There should be less spacing between the elements. Please look at the screenshots below and compare your page with the original. 
Your clone 👇 
Screen Shot 2020-06-09 at 10 37 00 PM
The original page 👇 
Screen Shot 2020-06-09 at 10 37 08 PM



****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****
 Good Luck and Happy Coding! 🍀 👩🏾‍💻


_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Pull request merged**
